!function(e){var n={};function r(t){if(n[t])return n[t].exports;var o=n[t]={i:t,l:!1,exports:{}};return e[t].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=n,r.d=function(e,n,t){r.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:t})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,n){if(1&n&&(e=r(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(r.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var o in e)r.d(t,o,function(n){return e[n]}.bind(null,o));return t},r.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(n,"a",n),n},r.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},r.p="",r(r.s="./src/js/main.js")}({"./src/js/_burger.js":
/*!***************************!*\
  !*** ./src/js/_burger.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var navigation = document.querySelector('.navigation');\nvar breadthWithBurger = 460;\nvar animationDelay = 300;\n\nwindow.onload = function () {\n  if (document.documentElement.clientWidth <= breadthWithBurger) {\n    navigation.classList.add('hidde');\n  }\n};\n\ndocument.querySelector('.burger').onclick = function () {\n  document.body.classList.toggle('stopScroll');\n  document.querySelector('.burger__icon').classList.toggle('burger__icon_active');\n\n  if (navigation.classList.contains('hidde')) {\n    navigation.classList.remove('hidde');\n    navigation.classList.add('toCenter');\n    setTimeout(function () {\n      navigation.classList.remove('toCenter');\n    }, animationDelay);\n  } else {\n    navigation.classList.add('toBottom');\n    setTimeout(function () {\n      navigation.classList.add('hidde');\n      navigation.classList.remove('toBottom');\n    }, animationDelay);\n  }\n};\n\nvar scroll;\nvar currentScrollPosition = 0;\n\nvar checkScrollLarge = function checkScrollLarge() {\n  scroll = window.pageYOffset;\n\n  if (scroll < currentScrollPosition) {\n    document.querySelector('.header').classList.remove('header_disable');\n  } else {\n    document.querySelector('.header').classList.add('header_disable');\n  }\n\n  currentScrollPosition = scroll;\n};\n\nvar checkScrollSmall = function checkScrollSmall() {\n  scroll = window.pageYOffset;\n\n  if (scroll < currentScrollPosition) {\n    document.querySelector('.burger').classList.remove('burger_disable');\n  } else {\n    document.querySelector('.burger').classList.add('burger_disable');\n  }\n\n  currentScrollPosition = scroll;\n};\n\nwindow.onscroll = function () {\n  if (window.screen.width > breadthWithBurger) {\n    checkScrollLarge();\n  } else {\n    checkScrollSmall();\n  }\n};\n\n//# sourceURL=webpack:///./src/js/_burger.js?")},"./src/js/_contents.js":
/*!*****************************!*\
  !*** ./src/js/_contents.js ***!
  \*****************************/
/*! no static exports found */function(module,exports){eval("var btn = document.querySelector('.contents__btn-more');\nvar items = document.querySelector('.contents__works-wrap').querySelectorAll('.contents__works-item');\n\nbtn.onclick = function () {\n  items.forEach(function (element) {\n    element.classList.remove('hidde');\n  });\n  btn.setAttribute('disabled', 'true');\n};\n\n//# sourceURL=webpack:///./src/js/_contents.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_burger */ "./src/js/_burger.js");\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_burger__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _contents__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./_contents */ "./src/js/_contents.js");\n/* harmony import */ var _contents__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_contents__WEBPACK_IMPORTED_MODULE_1__);\n\n\n\n//# sourceURL=webpack:///./src/js/main.js?')}});
//# sourceMappingURL=main.js.map
