!function(n){var e={};function r(t){if(e[t])return e[t].exports;var o=e[t]={i:t,l:!1,exports:{}};return n[t].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=n,r.c=e,r.d=function(n,e,t){r.o(n,e)||Object.defineProperty(n,e,{enumerable:!0,get:t})},r.r=function(n){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(n,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(n,"__esModule",{value:!0})},r.t=function(n,e){if(1&e&&(n=r(n)),8&e)return n;if(4&e&&"object"==typeof n&&n&&n.__esModule)return n;var t=Object.create(null);if(r.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:n}),2&e&&"string"!=typeof n)for(var o in n)r.d(t,o,function(e){return n[e]}.bind(null,o));return t},r.n=function(n){var e=n&&n.__esModule?function(){return n.default}:function(){return n};return r.d(e,"a",e),e},r.o=function(n,e){return Object.prototype.hasOwnProperty.call(n,e)},r.p="",r(r.s="./src/js/main.js")}({"./src/js/_burger.js":
/*!***************************!*\
  !*** ./src/js/_burger.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var burgerBtn = document.querySelector('.burger');\nvar nav = document.querySelector('.header__nav');\nvar btnLogin = document.querySelector('.header__login-btn');\nvar width = document.body.offsetWidth;\nburgerBtn.onclick = toggleBurgerMenu;\n\nfunction toggleBurgerMenu() {\n  burgerBtn.classList.toggle('burger_open');\n  nav.classList.toggle('header__nav_open');\n  btnLogin.classList.toggle('header__login-btn_show');\n  window.removeEventListener('resize', changeWidth);\n  document.body.classList.toggle('stop-scroll');\n\n  if (document.body.classList.contains('stop-scroll')) {\n    document.body.style.paddingRight = document.body.offsetWidth - width + 'px';\n  } else {\n    document.body.style.paddingRight = 0;\n  }\n\n  window.addEventListener('resize', changeWidth);\n}\n\nnav.addEventListener('click', function (event) {\n  if (nav.classList.contains('header__nav_open') && event.target.classList.contains('header__item-nav')) {\n    toggleBurgerMenu();\n  }\n});\nwindow.addEventListener('resize', changeWidth);\n\nfunction changeWidth() {\n  width = document.body.offsetWidth;\n}\n\n//# sourceURL=webpack:///./src/js/_burger.js?")},"./src/js/_header.js":
/*!***************************!*\
  !*** ./src/js/_header.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var header = document.querySelector('.header');\nvar toTop = 0;\nvar toDown = 0;\nvar toUp = 0;\nwindow.addEventListener('scroll', function () {\n  var currentScroll = window.scrollY;\n\n  if (currentScroll < 20) {\n    header.classList.remove('header_show');\n    toDown = 0;\n    toUp = 0;\n    return;\n  }\n\n  if (currentScroll > toTop) {\n    toTop = currentScroll;\n    toDown++;\n    toUp = 0;\n\n    if (toDown > 20) {\n      header.classList.add('header_show');\n    }\n  } else {\n    toTop = currentScroll;\n    toUp++;\n    toDown = 0;\n\n    if (toUp > 20) {\n      header.classList.remove('header_show');\n    }\n  }\n});\n\n//# sourceURL=webpack:///./src/js/_header.js?")},"./src/js/_timer.js":
/*!**************************!*\
  !*** ./src/js/_timer.js ***!
  \**************************/
/*! no static exports found */function(module,exports){eval("var dedline = new Date('June 29 2021 12:00:00');\nvar days = document.getElementById('days');\nvar hours = document.getElementById('hours');\nvar minuts = document.getElementById('min');\nvar secunds = document.getElementById('sec');\n\nvar currentDate = function currentDate() {\n  var gap = dedline - Date.now();\n  return {\n    days: Math.floor(gap / 1000 / 60 / 60 / 24),\n    hours: Math.floor(gap / 1000 / 60 / 60) % 24,\n    minuts: Math.floor(gap / 1000 / 60) % 60,\n    secunds: Math.floor(gap / 1000) % 60\n  };\n};\n\nwindow.onload = startTimer;\n\nfunction startTimer() {\n  secunds.innerHTML = currentDate().secunds;\n  minuts.innerHTML = currentDate().minuts;\n  hours.innerHTML = currentDate().hours;\n  days.innerHTML = currentDate().days;\n  setInterval(function () {\n    secunds.innerHTML = currentDate().secunds;\n\n    if (parseInt(minuts.innerHTML) > currentDate().minuts) {\n      minuts.innerHTML = currentDate().minuts;\n    }\n\n    if (parseInt(hours.innerHTML) > currentDate().hours) {\n      hours.innerHTML = currentDate().hours;\n    }\n\n    if (parseInt(days.innerHTML) > currentDate().days) {\n      days.innerHTML = currentDate().days;\n    }\n  });\n}\n\n//# sourceURL=webpack:///./src/js/_timer.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_burger */ "./src/js/_burger.js");\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_burger__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _header__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./_header */ "./src/js/_header.js");\n/* harmony import */ var _header__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_header__WEBPACK_IMPORTED_MODULE_1__);\n/* harmony import */ var _timer__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./_timer */ "./src/js/_timer.js");\n/* harmony import */ var _timer__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(_timer__WEBPACK_IMPORTED_MODULE_2__);\n\n\n\n\n//# sourceURL=webpack:///./src/js/main.js?')}});