!function(e){var n={};function r(t){if(n[t])return n[t].exports;var _=n[t]={i:t,l:!1,exports:{}};return e[t].call(_.exports,_,_.exports,r),_.l=!0,_.exports}r.m=e,r.c=n,r.d=function(e,n,t){r.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:t})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,n){if(1&n&&(e=r(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(r.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var _ in e)r.d(t,_,function(n){return e[n]}.bind(null,_));return t},r.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(n,"a",n),n},r.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},r.p="",r(r.s="./src/js/main.js")}({"./src/js/_burger.js":
/*!***************************!*\
  !*** ./src/js/_burger.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var burgerBtn = document.querySelector('.burger');\nvar nav = document.querySelector('.header__nav');\nvar btnLogin = document.querySelector('.header__login-btn');\nvar width = document.body.offsetWidth;\nburgerBtn.onclick = toggleBurgerMenu;\n\nfunction toggleBurgerMenu() {\n  burgerBtn.classList.toggle('burger_open');\n  nav.classList.toggle('header__nav_open');\n  btnLogin.classList.toggle('header__login-btn_show');\n  window.removeEventListener('resize', changeWidth);\n  document.body.classList.toggle('stop-scroll');\n\n  if (document.body.classList.contains('stop-scroll')) {\n    document.body.style.paddingRight = document.body.offsetWidth - width + 'px';\n  } else {\n    document.body.style.paddingRight = 0;\n  }\n\n  window.addEventListener('resize', changeWidth);\n}\n\nnav.addEventListener('click', function (event) {\n  if (nav.classList.contains('header__nav_open') && event.target.classList.contains('header__item-nav')) {\n    toggleBurgerMenu();\n  }\n});\nwindow.addEventListener('resize', changeWidth);\n\nfunction changeWidth() {\n  width = document.body.offsetWidth;\n}\n\n//# sourceURL=webpack:///./src/js/_burger.js?")},"./src/js/_header.js":
/*!***************************!*\
  !*** ./src/js/_header.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var header = document.querySelector('.header');\nvar toTop = 0;\nvar toDown = 0;\nvar toUp = 0;\nwindow.addEventListener('scroll', function () {\n  var currentScroll = window.scrollY;\n\n  if (currentScroll < 20) {\n    header.classList.remove('header_show');\n    toDown = 0;\n    toUp = 0;\n    return;\n  }\n\n  if (currentScroll > toTop) {\n    toTop = currentScroll;\n    toDown++;\n    toUp = 0;\n\n    if (toDown > 20) {\n      header.classList.add('header_show');\n    }\n  } else {\n    toTop = currentScroll;\n    toUp++;\n    toDown = 0;\n\n    if (toUp > 20) {\n      header.classList.remove('header_show');\n    }\n  }\n});\n\n//# sourceURL=webpack:///./src/js/_header.js?")},"./src/js/_timmer.js":
/*!***************************!*\
  !*** ./src/js/_timmer.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var deadline = Date.now() + 18 * 60000;\nvar sec = document.getElementById('sec');\nvar min = document.getElementById('min');\nvar flag = true;\nsetInterval(function () {\n  flag = false;\n  min.innerHTML = Math.round((deadline - Date.now()) / 60000);\n}, flag ? (60 - new Date().getSeconds()) * 1000 : 60000);\nsetInterval(function () {\n  sec.innerHTML = 60 - new Date().getSeconds() - 1;\n}, 1000);\n\n//# sourceURL=webpack:///./src/js/_timmer.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_burger */ "./src/js/_burger.js");\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_burger__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _header__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./_header */ "./src/js/_header.js");\n/* harmony import */ var _header__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_header__WEBPACK_IMPORTED_MODULE_1__);\n/* harmony import */ var _timmer__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./_timmer */ "./src/js/_timmer.js");\n/* harmony import */ var _timmer__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(_timmer__WEBPACK_IMPORTED_MODULE_2__);\n\n\n\n\n//# sourceURL=webpack:///./src/js/main.js?')}});