!function(e){var n={};function r(t){if(n[t])return n[t].exports;var _=n[t]={i:t,l:!1,exports:{}};return e[t].call(_.exports,_,_.exports,r),_.l=!0,_.exports}r.m=e,r.c=n,r.d=function(e,n,t){r.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:t})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,n){if(1&n&&(e=r(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(r.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var _ in e)r.d(t,_,function(n){return e[n]}.bind(null,_));return t},r.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(n,"a",n),n},r.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},r.p="",r(r.s="./src/js/main.js")}({"./src/js/_burger.js":
/*!***************************!*\
  !*** ./src/js/_burger.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var burgerBtn = document.querySelector('.burger');\nvar nav = document.querySelector('.header__nav-menu');\nvar width = document.body.offsetWidth;\nburgerBtn.onclick = toggleBurgerMenu;\n\nfunction toggleBurgerMenu() {\n  burgerBtn.classList.toggle('burger_open');\n  nav.classList.toggle('header__nav-menu_open');\n  document.body.classList.toggle('stop-scroll');\n\n  if (document.body.classList.contains('stop-scroll')) {\n    document.body.style.paddingRight = document.body.offsetWidth - width + 'px';\n  } else {\n    document.body.style.paddingRight = 0;\n  }\n}\n\nnav.addEventListener('click', function (event) {\n  if (nav.classList.contains('header__menu-links_open') && event.target.classList.contains('header__menu-link')) {\n    toggleBurgerMenu();\n  }\n});\n\n//# sourceURL=webpack:///./src/js/_burger.js?")},"./src/js/_header.js":
/*!***************************!*\
  !*** ./src/js/_header.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var header = document.querySelector('.header');\nvar toTop = 0;\nwindow.addEventListener('scroll', function () {\n  var currentScroll = window.scrollY;\n\n  if (currentScroll > toTop) {\n    toTop = currentScroll;\n    header.classList.add('header_hidden');\n\n    if (toTop > 100) {\n      header.style.background = 'rgba(255, 255, 255, 0.95)';\n    }\n  } else {\n    toTop = currentScroll;\n    header.classList.remove('header_hidden');\n\n    if (toTop < 100) {\n      header.style.background = 'transparent';\n    }\n  }\n});\n\n//# sourceURL=webpack:///./src/js/_header.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_burger */ "./src/js/_burger.js");\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_burger__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _header__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./_header */ "./src/js/_header.js");\n/* harmony import */ var _header__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_header__WEBPACK_IMPORTED_MODULE_1__);\n\n\n\n//# sourceURL=webpack:///./src/js/main.js?')}});