!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./src/js/main.js")}({"./src/js/_burger.js":
/*!***************************!*\
  !*** ./src/js/_burger.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var burgerBtn = document.querySelector('.burger');\nvar nav = document.querySelector('.header__menu-links');\nvar width = document.body.offsetWidth;\nburgerBtn.onclick = toggleBurgerMenu;\n\nfunction toggleBurgerMenu() {\n  burgerBtn.classList.toggle('burger_open');\n  nav.classList.toggle('header__menu-links_open');\n  document.body.classList.toggle('stop-scroll');\n\n  if (document.body.classList.contains('stop-scroll')) {\n    document.body.style.paddingRight = document.body.offsetWidth - width + 'px';\n  } else {\n    document.body.style.paddingRight = 0;\n  }\n}\n\nnav.addEventListener('click', function (event) {\n  if (nav.classList.contains('header__menu-links_open') && event.target.classList.contains('header__menu-link')) {\n    toggleBurgerMenu();\n  }\n});\n\n//# sourceURL=webpack:///./src/js/_burger.js?")},"./src/js/_card.js":
/*!*************************!*\
  !*** ./src/js/_card.js ***!
  \*************************/
/*! no static exports found */function(module,exports){eval('var duration = 300;\nvar wrapBtn = document.querySelector(\'.main\');\nvar btnClass = \'card__btn-cart\';\nvar colorStart = \'rgba(255, 255, 255, 1)\';\nvar colorEnd = \'rgba(1, 86, 255, 0.3)\';\nwrapBtn.addEventListener(\'mouseover\', function (event) {\n  if (!event.target.classList.contains(btnClass)) return;\n  if (event.relatedTarget.classList.contains(\'card__cart-icon\')) return;\n  animate({\n    timing: quad,\n    draw: hover,\n    duration: duration\n  }, event.target);\n});\nwrapBtn.addEventListener(\'mouseout\', function (event) {\n  if (!event.target.classList.contains(btnClass)) return;\n  if (event.relatedTarget.classList.contains(\'card__cart-icon\')) return;\n  animate({\n    timing: reverseQuad,\n    draw: hover,\n    duration: duration\n  }, event.target);\n});\n\nfunction animate(_ref, element) {\n  var timing = _ref.timing,\n      draw = _ref.draw,\n      duration = _ref.duration;\n  var start = performance.now();\n  requestAnimationFrame(function animate(time) {\n    var timeFraction = (time - start) / duration;\n    if (timeFraction > 1) timeFraction = 1;\n    var progress = timing(timeFraction);\n    draw(progress, element);\n\n    if (timeFraction < 1) {\n      requestAnimationFrame(animate);\n    }\n  });\n}\n\nfunction hover(progress, element) {\n  if (progress < 0.01) {\n    element.style.background = "linear-gradient(90deg, ".concat(colorStart, " 0%, ").concat(colorStart, "  ").concat(Math.round(progress * 100), "%, ").concat(colorStart, " 0%)");\n  } else if (progress < 0.99 && progress > 0.01) {\n    element.style.background = "linear-gradient(90deg, ".concat(colorStart, " 0%, ").concat(colorEnd, "  ").concat(Math.round(progress * 100), "%, ").concat(colorStart, " 100%)");\n  }\n}\n\nfunction quad(timeFraction) {\n  return Math.pow(timeFraction, 2);\n}\n\nfunction reverseQuad(timeFraction) {\n  return 1 - Math.pow(timeFraction, 2);\n}\n\n//# sourceURL=webpack:///./src/js/_card.js?')},"./src/js/_cart.js":
/*!*************************!*\
  !*** ./src/js/_cart.js ***!
  \*************************/
/*! no static exports found */function(module,exports){eval("var cartBtn = document.querySelector('.header__cart');\nvar width = document.body.offsetWidth;\ncartBtn.onclick = showCart;\n\nfunction showCart() {\n  document.querySelector('.cart').classList.toggle('hidde');\n  document.body.classList.toggle('stop-scroll');\n\n  if (document.body.classList.contains('stop-scroll')) {\n    document.body.style.paddingRight = document.body.offsetWidth - width + 'px';\n  } else {\n    document.body.style.paddingRight = 0;\n  }\n}\n\n//# sourceURL=webpack:///./src/js/_cart.js?")},"./src/js/_catalog.js":
/*!****************************!*\
  !*** ./src/js/_catalog.js ***!
  \****************************/
/*! no static exports found */function(module,exports){eval("function _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _unsupportedIterableToArray(arr) || _nonIterableSpread(); }\n\nfunction _nonIterableSpread() { throw new TypeError(\"Invalid attempt to spread non-iterable instance.\\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.\"); }\n\nfunction _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === \"string\") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === \"Object\" && o.constructor) n = o.constructor.name; if (n === \"Map\" || n === \"Set\") return Array.from(o); if (n === \"Arguments\" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }\n\nfunction _iterableToArray(iter) { if (typeof Symbol !== \"undefined\" && Symbol.iterator in Object(iter)) return Array.from(iter); }\n\nfunction _arrayWithoutHoles(arr) { if (Array.isArray(arr)) return _arrayLikeToArray(arr); }\n\nfunction _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) { arr2[i] = arr[i]; } return arr2; }\n\nvar sortWrap = document.querySelector('.catalog__sort-buttons');\nvar btnMore = document.querySelector('.catalog__booklet-more-btn');\nvar btnFilter = document.querySelector('.catalog__filter-btn');\nsortWrap.addEventListener('click', function (event) {\n  if (event.target.classList.contains('catalog__sort-selector')) {\n    event.target.classList.toggle('catalog__sort-selector_open');\n  } else if (event.target.classList.contains('catalog__sort-item')) {\n    var _votedItem$parentNode;\n\n    var votedItem = event.target;\n    var newItem = Array.from(votedItem.parentNode.children);\n    newItem.splice(newItem.indexOf(votedItem), 1);\n    newItem.unshift(votedItem);\n\n    (_votedItem$parentNode = votedItem.parentNode).append.apply(_votedItem$parentNode, _toConsumableArray(newItem));\n\n    event.target.parentNode.parentNode.classList.toggle('catalog__sort-selector_open');\n  }\n});\nbtnMore.addEventListener('click', openBooklet);\nbtnFilter.addEventListener('click', openFilter);\n\nfunction openBooklet() {\n  document.querySelector('.catalog__booklet-text').classList.toggle('catalog__booklet-text_open');\n}\n\nfunction openFilter() {\n  document.querySelector('.catalog__aside').classList.toggle('catalog__aside_open');\n}\n\n//# sourceURL=webpack:///./src/js/_catalog.js?")},"./src/js/_filter.js":
/*!***************************!*\
  !*** ./src/js/_filter.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var filterWrap = document.querySelector('.filter');\nfilterWrap.addEventListener('click', function (event) {\n  if (event.target.classList.contains('filter__item-category')) {\n    event.target.parentNode.classList.toggle('filter__item_close');\n    event.target.querySelector('.filter__arrow-icon').classList.toggle('filter__arrow-icon_close');\n  }\n});\n\n//# sourceURL=webpack:///./src/js/_filter.js?")},"./src/js/_footer.js":
/*!***************************!*\
  !*** ./src/js/_footer.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var wrapper = document.querySelector('.footer__links-items');\nwrapper.addEventListener('click', function (event) {\n  if (!event.target.classList.contains('footer__title-category')) return;\n  var category = event.target.parentNode;\n  category.querySelector('.footer__links-list').classList.toggle('footer__links-list_active');\n});\n\n//# sourceURL=webpack:///./src/js/_footer.js?")},"./src/js/_modal-contacts.js":
/*!***********************************!*\
  !*** ./src/js/_modal-contacts.js ***!
  \***********************************/
/*! no static exports found */function(module,exports){eval("var cartBtn = document.querySelector('.header__btn-modal');\nvar width = document.body.offsetWidth;\ncartBtn.addEventListener('click', showModal);\n\nfunction showModal() {\n  cartBtn.classList.toggle('header__btn-modal_open');\n  document.querySelector('.contacts').classList.toggle('hidde');\n  document.body.classList.toggle('stop-scroll');\n\n  if (document.body.classList.contains('stop-scroll')) {\n    document.body.style.paddingRight = document.body.offsetWidth - width + 'px';\n  } else {\n    document.body.style.paddingRight = 0;\n  }\n}\n\n//# sourceURL=webpack:///./src/js/_modal-contacts.js?")},"./src/js/_search.js":
/*!***************************!*\
  !*** ./src/js/_search.js ***!
  \***************************/
/*! no static exports found */function(module,exports){eval("var btnSearch = document.querySelector('.search-form__btn-search');\nvar inputSearch = document.querySelector('.search-form__input');\nbtnSearch.onclick = clickSearch;\n\nfunction clickSearch() {\n  if (inputSearch.value.length === 0) {\n    showSearch();\n  } else {\n    document.querySelector('.search-form').submit();\n  }\n}\n\nfunction showSearch() {\n  document.querySelector('.search-form__input').classList.toggle('search-form__input_open');\n  document.querySelector('.search-form__btn-reset').classList.toggle('search-form__btn-reset_open');\n}\n\n//# sourceURL=webpack:///./src/js/_search.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_burger */ \"./src/js/_burger.js\");\n/* harmony import */ var _burger__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_burger__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _search__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./_search */ \"./src/js/_search.js\");\n/* harmony import */ var _search__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_search__WEBPACK_IMPORTED_MODULE_1__);\n/* harmony import */ var _cart__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./_cart */ \"./src/js/_cart.js\");\n/* harmony import */ var _cart__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(_cart__WEBPACK_IMPORTED_MODULE_2__);\n/* harmony import */ var _modal_contacts__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./_modal-contacts */ \"./src/js/_modal-contacts.js\");\n/* harmony import */ var _modal_contacts__WEBPACK_IMPORTED_MODULE_3___default = /*#__PURE__*/__webpack_require__.n(_modal_contacts__WEBPACK_IMPORTED_MODULE_3__);\n/* harmony import */ var _footer__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./_footer */ \"./src/js/_footer.js\");\n/* harmony import */ var _footer__WEBPACK_IMPORTED_MODULE_4___default = /*#__PURE__*/__webpack_require__.n(_footer__WEBPACK_IMPORTED_MODULE_4__);\n/* harmony import */ var _card__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ./_card */ \"./src/js/_card.js\");\n/* harmony import */ var _card__WEBPACK_IMPORTED_MODULE_5___default = /*#__PURE__*/__webpack_require__.n(_card__WEBPACK_IMPORTED_MODULE_5__);\n/* harmony import */ var _catalog__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ./_catalog */ \"./src/js/_catalog.js\");\n/* harmony import */ var _catalog__WEBPACK_IMPORTED_MODULE_6___default = /*#__PURE__*/__webpack_require__.n(_catalog__WEBPACK_IMPORTED_MODULE_6__);\n/* harmony import */ var _filter__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ./_filter */ \"./src/js/_filter.js\");\n/* harmony import */ var _filter__WEBPACK_IMPORTED_MODULE_7___default = /*#__PURE__*/__webpack_require__.n(_filter__WEBPACK_IMPORTED_MODULE_7__);\n\n\n\n // import './_hot-products'\n// import './_new-products'\n// import './_custom-builds'\n// import './_laptops'\n// import './_decstops'\n// import './_monitors'\n// import './_brands'\n// import './_news'\n// import './_responses'\n\n\n // import './_outplay'\n// import './_details'\n// catalog\n\n\n\n\n//# sourceURL=webpack:///./src/js/main.js?")}});